version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - restore_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: make test
      - store_test_results:
          path: junit-reports
  coverage:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - restore_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run karma start karma.conf.coverage.js
      - store_test_results:
          path: junit-reports
      - run: yarn run codecov
  publish:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: npm publish .
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - coverage:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
